buildscript {
    repositories {
        mavenCentral()
        maven { name = "forge"; url = "https://maven.minecraftforge.net/" }
        maven { url = "https://repo.spongepowered.org/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = "0.3"
group = "com.elementmod"
archivesBaseName = "elementmod"
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = "1.12.2-14.23.5.2860"
    runDir = "run"
    mappings = "stable_39"
}
