name: Unzip
on: push
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip and push
        run: |
          if ls *.zip 1> /dev/null 2>&1; then
            unzip -o *.zip
            cp -r elementmod/. .
            rm -rf elementmod *.zip
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add -A
            git commit -m "Mod dosyalari acildi"
            git push
          fi
